
version: 2

sources:
  - name: landing
    database: jumanjian  
    tables:
      - name: resorts_maven
      - name: snow_maven

models:
  - name: stg_resorts
    description: "Initial pull cleaned Resort column"
  - name: stg_snow
    description: "Initial pull"